/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import chartStatics.ModelChart;
import java.awt.Color;

/**
 *
 * @author trant
 */
public class Management_Statistical_GUI extends javax.swing.JPanel {

    /**
     * Creates new form Management_Statistical_GUI
     */
    public Management_Statistical_GUI() {
        initComponents();
        chart.addLegend("Thu vào", Color.YELLOW);
        chart.addLegend("Chi ra", Color.RED);
        chart.addLegend("Doanh thu", Color.GREEN);
        chart.addData(new ModelChart("Ngày 3/12/2021", new double[]{350,100,250}));
        chart.addData(new ModelChart("Ngày 4/12/2021", new double[]{750,200,550}));
        chart.addData(new ModelChart("Ngày 5/12/2021", new double[]{450,200,250}));
        chart.addData(new ModelChart("Ngày 6/12/2021", new double[]{350,100,250}));
        chart.addData(new ModelChart("Ngày 7/12/2021", new double[]{550,300,250}));
        chart.addData(new ModelChart("Ngày 8/12/2021", new double[]{850,200,650}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart = new chartStatics.Chart();

        setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 1096, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private chartStatics.Chart chart;
    // End of variables declaration//GEN-END:variables
}
