/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author trant
 */
public class Management_extrafee_GUI extends javax.swing.JPanel {

    /**
     * Creates new form Management_extrafee_GUI
     */
    public Management_extrafee_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        txtSearchExfee = new UserControl.TextFieldAnimation();
        btnAddExFee = new UserControl.GradientButtom();
        btnRepairExfee = new UserControl.GradientButtom();
        btnDeleteExfee = new UserControl.GradientButtom();
        Bottom = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_ExtraFee_Management = new UserControl.TableDark();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        Top.setBackground(new java.awt.Color(0, 102, 102));
        Top.setOpaque(false);

        txtSearchExfee.setAnimationColor(new java.awt.Color(0, 0, 51));
        txtSearchExfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchExfeeActionPerformed(evt);
            }
        });

        btnAddExFee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_add_30px.png"))); // NOI18N
        btnAddExFee.setText("Thêm");
        btnAddExFee.setColor1(new java.awt.Color(51, 0, 153));
        btnAddExFee.setColor2(new java.awt.Color(102, 0, 102));
        btnAddExFee.setFont(new java.awt.Font("UTM Alexander", 0, 12)); // NOI18N

        btnRepairExfee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_screwdriver_emoji_30px.png"))); // NOI18N
        btnRepairExfee.setText("Sửa");
        btnRepairExfee.setColor1(new java.awt.Color(0, 102, 102));
        btnRepairExfee.setColor2(new java.awt.Color(51, 102, 0));
        btnRepairExfee.setFont(new java.awt.Font("UTM Alexander", 0, 12)); // NOI18N

        btnDeleteExfee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_delete_30px.png"))); // NOI18N
        btnDeleteExfee.setText("Xóa");
        btnDeleteExfee.setColor1(new java.awt.Color(255, 255, 0));
        btnDeleteExfee.setColor2(new java.awt.Color(255, 0, 0));
        btnDeleteExfee.setFont(new java.awt.Font("UTM Alexander", 0, 12)); // NOI18N

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearchExfee, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnAddExFee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnRepairExfee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnDeleteExfee, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddExFee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDeleteExfee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRepairExfee, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSearchExfee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(Top, java.awt.BorderLayout.PAGE_START);

        Bottom.setBackground(new java.awt.Color(0, 0, 0));
        Bottom.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));

        table_ExtraFee_Management.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên phí", "Số tiền", "Hữu hiệu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_ExtraFee_Management.setGridColor(new java.awt.Color(51, 51, 51));
        table_ExtraFee_Management.setRowHeight(50);
        jScrollPane2.setViewportView(table_ExtraFee_Management);

        Bottom.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(Bottom, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchExfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchExfeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchExfeeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Top;
    private UserControl.GradientButtom btnAddExFee;
    private UserControl.GradientButtom btnDeleteExfee;
    private UserControl.GradientButtom btnRepairExfee;
    private javax.swing.JScrollPane jScrollPane2;
    private UserControl.TableDark table_ExtraFee_Management;
    private UserControl.TextFieldAnimation txtSearchExfee;
    // End of variables declaration//GEN-END:variables
}
