/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author trant
 */
public class Management_Bill_GUI extends javax.swing.JPanel {

    /**
     * Creates new form Management_Bill_GUI
     */
    public Management_Bill_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Top = new javax.swing.JPanel();
        btnExportList = new UserControl.GradientButtom();
        cbbFilterStaff = new UserControl.JComboboxCustom();
        cbbFilterIdTable = new UserControl.JComboboxCustom();
        cbbFilterTimeBill = new UserControl.JComboboxCustom();
        btnFilter = new UserControl.GradientButtom();
        Bottom = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Bill_Management = new UserControl.TableDark();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        Top.setBackground(new java.awt.Color(0, 102, 102));
        Top.setOpaque(false);

        btnExportList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_print_30px.png"))); // NOI18N
        btnExportList.setText("Xuất");
        btnExportList.setColor1(new java.awt.Color(0, 102, 102));
        btnExportList.setColor2(new java.awt.Color(51, 102, 0));
        btnExportList.setFont(new java.awt.Font("UTM Alexander", 0, 12)); // NOI18N

        cbbFilterStaff.setBackground(new java.awt.Color(254, 201, 149));
        cbbFilterStaff.setSelectedIndex(-1);
        cbbFilterStaff.setLabeText("Nhân viên lập");

        cbbFilterIdTable.setBackground(new java.awt.Color(254, 201, 149));
        cbbFilterIdTable.setSelectedIndex(-1);
        cbbFilterIdTable.setLabeText("Số bàn");

        cbbFilterTimeBill.setBackground(new java.awt.Color(254, 201, 149));
        cbbFilterTimeBill.setSelectedIndex(-1);
        cbbFilterTimeBill.setLabeText("Ngày lập hóa đơn");

        btnFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_filter_30px.png"))); // NOI18N
        btnFilter.setText("Lọc");
        btnFilter.setColor1(new java.awt.Color(102, 102, 255));
        btnFilter.setColor2(new java.awt.Color(153, 0, 255));
        btnFilter.setFont(new java.awt.Font("UTM Alexander", 0, 12)); // NOI18N

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbbFilterStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbbFilterTimeBill, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbbFilterIdTable, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExportList, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbFilterIdTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExportList, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbbFilterStaff, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbbFilterTimeBill, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(Top, java.awt.BorderLayout.PAGE_START);

        Bottom.setBackground(new java.awt.Color(0, 0, 0));
        Bottom.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(51, 51, 51));

        table_Bill_Management.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nhân viên lập", "Bàn", "Thời gian vào", "Thời gian ra", "Tổng phụ thu", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Bill_Management.setGridColor(new java.awt.Color(51, 51, 51));
        table_Bill_Management.setRowHeight(50);
        jScrollPane2.setViewportView(table_Bill_Management);

        Bottom.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(Bottom, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Top;
    private UserControl.GradientButtom btnExportList;
    private UserControl.GradientButtom btnFilter;
    private UserControl.JComboboxCustom cbbFilterIdTable;
    private UserControl.JComboboxCustom cbbFilterStaff;
    private UserControl.JComboboxCustom cbbFilterTimeBill;
    private javax.swing.JScrollPane jScrollPane2;
    private UserControl.TableDark table_Bill_Management;
    // End of variables declaration//GEN-END:variables
}
